spring:
  application:
    name: shipment-workflow
  temporal:
    connection:
      target: 127.0.0.1:7233
    namespace: default
    workers-auto-discovery:
      packages:
        - com.sayanth.ranjith.temporal.shipment_workflow
    workers:
      - task-queue: order-shipment-worker
        name: order-shipment-worker
